# Generated by Django 6.0.3 on 2026-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_organization_description_organization_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
