# Generated by Django 6.0.3 on 2026-04-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_placement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='status',
        ),
    ]
