# Generated by Django 6.0.3 on 2026-04-16 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0003_placement_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_type', models.CharField(choices=[('workplace', 'Workplace Supervisor'), ('academic', 'Academic Supervisor')], max_length=20)),
                ('score', models.IntegerField()),
                ('comments', models.TextField()),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.placement')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('placement', 'supervisor')},
            },
        ),
        migrations.CreateModel(
            name='CriteriaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='supervision.evaluation')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.evaluationcriteria')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('tasks', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('attendance_days', models.PositiveIntegerField(default=5)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internships.placement')),
            ],
        ),
    ]
