# Generated by Django 6.0.3 on 2026-04-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_alter_weeklylog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriteria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
