# Generated by Django 6.0.3 on 2026-05-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0005_alter_application_unique_together'),
        ('supervision', '0004_evaluationcriteria_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklylog',
            unique_together={('placement', 'week_number')},
        ),
    ]
