# Generated by Django 6.0.3 on 2026-04-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_evaluation_final_grade_evaluation_is_final_and_more'),
        ('supervision', '0005_criteriascore'),
    ]

    operations = [
    ]
