# Generated by Django 6.0.3 on 2026-05-07 01:28
from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0006_alter_evaluation_final_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='final_grade',
            field=models.FloatField(
                null=True,
                blank=True,
                default=0
            ),
        ),
    ]
