# Generated by Django 6.0.3 on 2026-06-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0007_add_final_grade_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='weekly_logs/'),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklylog',
            name='supervisor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
