# Generated by Django 6.0.3 on 2026-06-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0008_weeklylog_attachment_alter_weeklylog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklylog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
