# Generated by Django 6.0.3 on 2026-06-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0009_weeklylog_reviewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklylog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
